<?php

namespace Lc\LcBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Lc\LcBundle\Entity\Feeling;

/**
 * FeelingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeelingRepository extends EntityRepository
{
    public function getUserFeeling($uid = null)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT f FROM
			LcLcBundle:Feeling f
			WHERE f.user = :id1
			AND f.is_active = :is or
			(f.user IN (SELECT IDENTITY (nf.user2) FROM LcLcBundle:Friend nf where nf.user1 = :id1 and
			nf.is_confirmed = :is and nf.status = :is) and f.user IN (SELECT IDENTITY (na.user2) FROM LcLcBundle:Friend na
			where na.user1 = :id1 and na.is_confirmed = :is and na.status = :is))
			order by f.created_at DESC'
            )
            ->setParameters(array(
                           'id1' => $uid,
                           'is' => 1,
                            ));

        return $query;
    }

    public function getUserFeelingPreview($uid = null)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT f FROM
			LcLcBundle:Feeling f
			WHERE f.user = :id1
			AND f.is_active = :is
			order by f.created_at DESC'
            )
            ->setParameters(array(
                           'id1' => $uid,
                           'is' => 1,
                            ));

        return $query;
    }

    public function countUserFeelingPreview($uid = null)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT f FROM
			LcLcBundle:Feeling f
			WHERE f.user = :id1
			AND f.is_active = :is
			order by f.created_at DESC'
            )
            ->setParameters(array(
                           'id1' => $uid,
                           'is' => 1,
                            ));

        return count($query->getResult());
    }

    public function countUserFeeling($uid = null)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT f FROM
			LcLcBundle:Feeling f
			WHERE f.user = :id1
			AND f.is_active = :is or
			(f.user IN (SELECT IDENTITY (nf.user2) FROM LcLcBundle:Friend nf where nf.user1 = :id1 and
			nf.is_confirmed = :is and nf.status = :is) and f.user IN (SELECT IDENTITY (na.user2) FROM LcLcBundle:Friend na
			where na.user1 = :id1 and na.is_confirmed = :is and na.status = :is))
			order by f.created_at DESC'
            )
            ->setParameters(array(
                           'id1' => $uid,
                           'is' => 1,
                            ));

        $love = $query->getResult();

        $love = count($love);

        return $love;
    }
}
