<?php

namespace Lc\LcBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Lc\LcBundle\Entity\Feeling;

/**
 * FeelingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeelingRepository extends EntityRepository
{
	public function getUserFeeling($uid = null)
	{
		$query = $this->getEntityManager()
			->createQuery('SELECT f FROM
			LcLcBundle:Feeling f INNER JOIN LcLcBundle:Friend fr with f.user= fr.user2
			WHERE fr.user1 = :id1
			OR fr.user2 = :id1
			AND f.is_active = :is
			order by f.created_at DESC'
			)
			->setMaxResults(50)
			->setParameters(array(
						   'id1' => $uid,
						   'is' => 1,
							));
		
		return $query->getResult();
	}
}
