<?php

namespace Lc\LcBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Lc\LcBundle\Entity\Flike;
/**
 * FlikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlikeRepository extends EntityRepository
{
	public function checkLiked($user = null, $feel = null){
		$query = $this->createQueryBuilder('l')
		->where('l.user = :uid')
		->setParameter('uid', $user)
		->andWhere('l.feeling = :fe')
		->setParameter('fe', $feel)
		->setMaxResults(1)
		->getQuery();
		
		try{
            $flike = $query->getSingleResult();
        } catch(\Doctrine\Orm\NoResultException $e){
            $flike = null;
        }
		return $flike;
	}
}
