<?php

namespace Lc\LcBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserProviderInterface
{
   public function loadUserByUsername($username) {
     return $this->getEntityManager()
         ->createQuery('SELECT u FROM
         LcLcBundle:User u
         WHERE u.username = :username
         OR u.email = :username
         AND u.is_active = 1'
         )
         ->setParameters(array(
                       'username' => $username
                        ))
         ->getOneOrNullResult();
    }
 
    public function refreshUser(UserInterface $user) {
        return $this->loadUserByUsername($user->getUsername());
    }
 
    public function supportsClass($class) {
        return $class === 'Lc\LcBundle\Entity\User';
    }
    
    public function loadOthers($sex) {
     $query = $this->createQueryBuilder('u')
            ->where('u.sex != :sex')
            ->setParameter('sex', $sex)
            ->andWhere('u.is_active = :active')
            ->setParameter('active', 1)
            ->setMaxResults(8)
            ->getQuery();
 
        try {
            $love = $query->getResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
        $love = null;
          }
 
        return $love;
    }
 
}
