adminmclist:
    path:     /
    defaults: { _controller: "LcLcBundle:Adminmclist:index" }

adminmclist_show:
    path:     /{id}/show
    defaults: { _controller: "LcLcBundle:Adminmclist:show" }

adminmclist_new:
    path:     /new
    defaults: { _controller: "LcLcBundle:Adminmclist:new" }

adminmclist_create:
    path:     /create
    defaults: { _controller: "LcLcBundle:Adminmclist:create" }
    requirements: { _method: post }

adminmclist_edit:
    path:     /{id}/edit
    defaults: { _controller: "LcLcBundle:Adminmclist:edit" }

adminmclist_update:
    path:     /{id}/update
    defaults: { _controller: "LcLcBundle:Adminmclist:update" }
    requirements: { _method: post|put }

adminmclist_delete:
    path:     /{id}/delete
    defaults: { _controller: "LcLcBundle:Adminmclist:delete" }
    requirements: { _method: post|delete }
