flike:
    path:     /
    defaults: { _controller: "LcLcBundle:Flike:index" }

flike_show:
    path:     /{id}/show
    defaults: { _controller: "LcLcBundle:Flike:show" }

flike_new:
    path:     /new
    defaults: { _controller: "LcLcBundle:Flike:new" }

flike_create:
    path:     /create/{feel}/{page}
    defaults: { _controller: "LcLcBundle:Flike:create" }

flike_edit:
    path:     /{id}/edit
    defaults: { _controller: "LcLcBundle:Flike:edit" }

flike_update:
    path:     /{id}/update
    defaults: { _controller: "LcLcBundle:Flike:update" }
    requirements: { _method: post|put }

flike_delete:
    path:     /{id}/delete
    defaults: { _controller: "LcLcBundle:Flike:delete" }
    requirements: { _method: post|delete }
