friend:
    path:     /
    defaults: { _controller: "LcLcBundle:Friend:index" }

friend_show:
    path:     /list/{token}
    defaults: { _controller: "LcLcBundle:Friend:show" }
    
friend_block:
    path:     /{token}/block
    defaults: { _controller: "LcLcBundle:Friend:block" }
    
friend_fall:
    path:     /fall/{token}
    defaults: { _controller: "LcLcBundle:Friend:showfall" }

friend_new:
    path:     /new
    defaults: { _controller: "LcLcBundle:Friend:new" }

friend_create:
    path:     /make/{token}
    defaults: { _controller: "LcLcBundle:Friend:create" }

friend_edit:
    path:     /{id}/edit
    defaults: { _controller: "LcLcBundle:Friend:edit" }

friend_update:
    path:     /{token}/love
    defaults: { _controller: "LcLcBundle:Friend:update" }

friend_delete:
    path:     /{token}/reject
    defaults: { _controller: "LcLcBundle:Friend:delete" }
