friend:
    path:     /
    defaults: { _controller: "LcLcBundle:Friend:index" }

friend_show:
    path:     /{id}/show
    defaults: { _controller: "LcLcBundle:Friend:show" }

friend_new:
    path:     /new
    defaults: { _controller: "LcLcBundle:Friend:new" }

friend_create:
    path:     /make/{token}
    defaults: { _controller: "LcLcBundle:Friend:create" }

friend_edit:
    path:     /{id}/edit
    defaults: { _controller: "LcLcBundle:Friend:edit" }

friend_update:
    path:     /{id}/update
    defaults: { _controller: "LcLcBundle:Friend:update" }
    requirements: { _method: post|put }

friend_delete:
    path:     /{id}/delete
    defaults: { _controller: "LcLcBundle:Friend:delete" }
    requirements: { _method: post|delete }
