gallery:
    path:     /
    defaults: { _controller: "LcLcBundle:Gallery:index" }

gallery_show:
    path:     /{id}/show
    defaults: { _controller: "LcLcBundle:Gallery:show" }

gallery_new:
    path:     /new
    defaults: { _controller: "LcLcBundle:Gallery:new" }

gallery_create:
    path:     /create
    defaults: { _controller: "LcLcBundle:Gallery:create" }
    requirements: { _method: post }

gallery_edit:
    path:     /{id}/edit
    defaults: { _controller: "LcLcBundle:Gallery:edit" }

gallery_update:
    path:     /{id}/update
    defaults: { _controller: "LcLcBundle:Gallery:update" }
    requirements: { _method: post|put }

gallery_delete:
    path:     /{id}/delete
    defaults: { _controller: "LcLcBundle:Gallery:delete" }
    requirements: { _method: post|delete }
