job:
    path:     /
    defaults: { _controller: "LcLcBundle:Job:index" }

job_show:
    path:     /{id}/show
    defaults: { _controller: "LcLcBundle:Job:show" }

job_new:
    path:     /new
    defaults: { _controller: "LcLcBundle:Job:new" }

job_create:
    path:     /create
    defaults: { _controller: "LcLcBundle:Job:create" }
    requirements: { _method: post }

job_edit:
    path:     /{id}/edit
    defaults: { _controller: "LcLcBundle:Job:edit" }

job_update:
    path:     /{id}/update
    defaults: { _controller: "LcLcBundle:Job:update" }
    requirements: { _method: post|put }

job_delete:
    path:     /{id}/delete
    defaults: { _controller: "LcLcBundle:Job:delete" }
    requirements: { _method: post|delete }
