priviledge:
    path:     /
    defaults: { _controller: "LcLcBundle:Priviledge:index" }

priviledge_show:
    path:     /{id}/show
    defaults: { _controller: "LcLcBundle:Priviledge:show" }

priviledge_new:
    path:     /new
    defaults: { _controller: "LcLcBundle:Priviledge:new" }

priviledge_create:
    path:     /create
    defaults: { _controller: "LcLcBundle:Priviledge:create" }
    requirements: { _method: post }

priviledge_edit:
    path:     /{id}/edit
    defaults: { _controller: "LcLcBundle:Priviledge:edit" }

priviledge_update:
    path:     /{id}/update
    defaults: { _controller: "LcLcBundle:Priviledge:update" }
    requirements: { _method: post|put }

priviledge_delete:
    path:     /{id}/delete
    defaults: { _controller: "LcLcBundle:Priviledge:delete" }
    requirements: { _method: post|delete }
