profile:
    path:     /
    defaults: { _controller: "LcLcBundle:Profile:index" }
profile_data:
    path:     /data
    defaults: { _controller: "LcLcBundle:Profile:profile" }

profile_show:
    path:     /detail
    defaults: { _controller: "LcLcBundle:Profile:show" }
    
profile_see:
    path:     /{token}/see
    defaults: { _controller: "LcLcBundle:Profile:see" }

profile_new:
    path:     /new
    defaults: { _controller: "LcLcBundle:Profile:new" }

profile_create:
    path:     /create
    defaults: { _controller: "LcLcBundle:Profile:create" }
    requirements: { _method: post }

profile_edit:
    path:     /{id}/edit
    defaults: { _controller: "LcLcBundle:Profile:edit" }

profile_update:
    path:     /{id}/update
    defaults: { _controller: "LcLcBundle:Profile:update" }
    requirements: { _method: post|put }

profile_delete:
    path:     /{id}/delete
    defaults: { _controller: "LcLcBundle:Profile:delete" }
    requirements: { _method: post|delete }
