sallary:
    path:     /
    defaults: { _controller: "LcLcBundle:Sallary:index" }

sallary_show:
    path:     /{id}/show
    defaults: { _controller: "LcLcBundle:Sallary:show" }

sallary_new:
    path:     /new
    defaults: { _controller: "LcLcBundle:Sallary:new" }

sallary_create:
    path:     /create
    defaults: { _controller: "LcLcBundle:Sallary:create" }
    requirements: { _method: post }

sallary_edit:
    path:     /{id}/edit
    defaults: { _controller: "LcLcBundle:Sallary:edit" }

sallary_update:
    path:     /{id}/update
    defaults: { _controller: "LcLcBundle:Sallary:update" }
    requirements: { _method: post|put }

sallary_delete:
    path:     /{id}/delete
    defaults: { _controller: "LcLcBundle:Sallary:delete" }
    requirements: { _method: post|delete }
