sex:
    path:     /
    defaults: { _controller: "LcLcBundle:Sex:index" }

sex_show:
    path:     /{id}/show
    defaults: { _controller: "LcLcBundle:Sex:show" }

sex_new:
    path:     /new
    defaults: { _controller: "LcLcBundle:Sex:new" }

sex_create:
    path:     /create
    defaults: { _controller: "LcLcBundle:Sex:create" }
    requirements: { _method: post }

sex_edit:
    path:     /{id}/edit
    defaults: { _controller: "LcLcBundle:Sex:edit" }

sex_update:
    path:     /{id}/update
    defaults: { _controller: "LcLcBundle:Sex:update" }
    requirements: { _method: post|put }

sex_delete:
    path:     /{id}/delete
    defaults: { _controller: "LcLcBundle:Sex:delete" }
    requirements: { _method: post|delete }
