user:
    path:     /heaven/user
    defaults: { _controller: "LcLcBundle:User:index" }
user_search:
    path:     /heaven/cari
    defaults: { _controller: "LcLcBundle:User:search" }
user_others:
    path:     /heaven/all
    defaults: { _controller: "LcLcBundle:User:all" }
user_wait:
 path: /thanks
 defaults: { _controller: "LcLcBundle:User:wait"}

user_foto:
 path: /heaven/foto
 defaults: { _controller: "LcLcBundle:User:foto"}

user_pass:
 path: /heaven/pass
 defaults: { _controller: "LcLcBundle:User:changePasswd"}
user_show:
    path:     /heaven/{id}/show
    defaults: { _controller: "LcLcBundle:User:show" }

user_new:
    path:     /new
    defaults: { _controller: "LcLcBundle:User:new" }

user_create:
    path:     /create
    defaults: { _controller: "LcLcBundle:User:create" }
    requirements: { _method: post }

user_edit:
    path:     /heaven/{id}/edit
    defaults: { _controller: "LcLcBundle:User:edit" }
user_activate:
    path:     /activate/{token}
    defaults: { _controller: "LcLcBundle:User:activate" }

user_update:
    path:     /heaven/{token}/renew
    defaults: { _controller: "LcLcBundle:User:update" }
    requirements: { _method: post|put }

user_delete:
    path:     /heaven/{id}/delete
    defaults: { _controller: "LcLcBundle:User:delete" }
    requirements: { _method: post|delete }
