user:
    path:     /
    defaults: { _controller: "LcLcBundle:User:index" }
user_wait:
 path: /thanks
 defaults: { _controller: "LcLcBundle:User:wait"}
user_show:
    path:     /{id}/show
    defaults: { _controller: "LcLcBundle:User:show" }

user_new:
    path:     /new
    defaults: { _controller: "LcLcBundle:User:new" }

user_create:
    path:     /create
    defaults: { _controller: "LcLcBundle:User:create" }
    requirements: { _method: post }

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "LcLcBundle:User:edit" }
user_activate:
    path:     /activate/{token}
    defaults: { _controller: "LcLcBundle:User:activate" }

user_update:
    path:     /{token}/update
    defaults: { _controller: "LcLcBundle:User:update" }
    requirements: { _method: post|put }

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "LcLcBundle:User:delete" }
    requirements: { _method: post|delete }
