Lc\LcBundle\Entity\Admin:
 type: entity
 table: admin
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  name:
   type: string
   length: 255
  password:
   type: string
   length: 255
  email:
   type: string
   length: 255
   unique: true
  is_active: 
   type: boolean
  token: 
   type: string
   length: 255
   unique: true
  created_at:
   type: datetime
  updated_at:
   type: datetime
   nullable: true
 oneToMany:
  jobs:
   targetEntity: Job
   mappedBy: category
 manyToMany:
  affiliates:
   targetEntity: Affiliate
   mappedBy: categories
