Lc\LcBundle\Entity\Alcoholic:
 type: entity
 table: alcoholic
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  name:
   type: string
   length: 255
  is_active:
   type: boolean
  created_at:
   type: datetime
  updated_at:
   type: datetime
   nullable: true
  token:
   type: string
   length: 255
   unique: true
 oneToOne:
  usercriteria:
   targetEntity: Usercriteria
   mappedBy: alcoholic
  profile:
   targetEntity: Profile
   mappedBy: alcoholic
