Lc\LcBundle\Entity\Chat:
 type: entity
 table: chat
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  id_1:
   type: integer
  id_2:
   type: integer
  message:
   type: text
  created_at:
   type: datetime
  updated_at:
   type: datetime
   nullable: true
  token:
   type: string
   length: 255
 oneToMany:
  jobs:
   targetEntity: Job
   mappedBy: category
 manyToMany:
  affiliates:
   targetEntity: Affiliate
   mappedBy: categories
