Lc\LcBundle\Entity\City:
 type: entity
 table: city
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  name:
   type: string
   length: 255
  is_active:
   type: boolean
  created_at:
   type: datetime
  updated_at:
   type: datetime
   nullable: true
  token:
   type: string
   length: 255
   unique: true
 manyToOne:
  province:
   targetEntity: Province
   inversedBy: city
   joinColumn:
    name: province_id
    referencedColumnName: id
 oneToOne:
  usercriteria:
   targetEntity: Usercriteria
   mappedBy: city
  profile:
   targetEntity: Profile
   mappedBy: city
