Lc\LcBundle\Entity\Criteria:
 type: entity
 table: criteria
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  name:
   type: string
   length: 255
   unique: true
  is_active:
   type: boolean
  token:
   type: string
   length: 255
   unique: true
 oneToMany:
  jobs:
   targetEntity: Job
   mappedBy: category
 manyToMany:
  affiliates:
   targetEntity: Affiliate
   mappedBy: categories
