Lc\LcBundle\Entity\Fcomment:
 type: entity
 table: fcomment
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  comment:
   type: text
  is_publish:
   type: boolean
  token: 
   type: string
   length: 255
   unique: true
  created_at:
   type: datetime
  updated_at:
   type: datetime
   nullable: true
 oneToMany:
  jobs:
   targetEntity: Job
   mappedBy: category
 manyToMany:
  affiliates:
   targetEntity: Affiliate
   mappedBy: categories
