Lc\LcBundle\Entity\Feeling:
 type: entity
 repositoryClass: Lc\LcBundle\Repository\FeelingRepository
 table: feeling
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  feel:
   type: text
  liked:
   type: integer
   nullable: true
  shared:
   type: integer
   nullable: true
  foto:
   type: string
   length: 255
   nullable: true
  commented:
   type: integer
   nullable: true
  is_active:
   type: boolean
  channel:
   type: string
   length: 255
   nullable: true
  created_at:
   type: datetime
  updated_at:
   type: datetime
   nullable: true
  token:
   type: string
   length: 255
   unique: true
 oneToMany:
  children:
   targetEntity: Feeling
   mappedBy: parent
  fcomment:
   targetEntity: Fcomment
   mappedBy: feeling
  flike:
   targetEntity: Flike
   mappedBy: feeling
  fshare:
   targetEntity: Fshare
   mappedBy: feeling
  orderan:
   targetEntity: Orderan
   mappedBy: feeling
 manyToOne:
  parent:
   targetEntity: Feeling
   inversedBy: children
   joinColumn:
    name: shared
    referencedColumnName: id
  user:
   targetEntity: User
   inversedBy: feeling
   joinColumn:
    name: user_id
    referencedColumnName: id
 lifecycleCallbacks:
  prePersist: [ preUpload, setCreatedAtValue, setTokenValue ]
  preUpdate: [ setUpdatedAtValue ]
  postPersist: [ upload ]
