Lc\LcBundle\Entity\Flike:
 type: entity
 repositoryClass: Lc\LcBundle\Repository\FlikeRepository
 table: flike
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  created_at: 
   type: datetime
  updated_at:
   type: datetime
   nullable: true
  status:
   type: boolean
  token:
   type: string
   length: 255
   unique: true
 manyToOne:
  feeling:
   targetEntity: Feeling
   inversedBy: flike
   joinColumn:
    name: feeling_id
    referencedColumnName: id
  user:
   targetEntity: User
   inversedBy: flike
   joinColumn:
    name: user_id
    referencedColumnName: id
 lifecycleCallbacks:
  prePersist: [ setCreatedAtValue, setTokenValue ]
  preUpdate: [ setUpdatedAtValue ]
