Lc\LcBundle\Entity\Friend:
 type: entity
 repositoryClass: Lc\LcBundle\Repository\FriendRepository
 table: friend
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  id_1: 
   type: string
   length: 255
  id_2:
   type: string
   length: 255
  status:
   type: boolean
  is_confirmed:
   type: boolean
  created_at:
   type: datetime
  updated_at:
   type: datetime
   nullable: true
  token:
   type: string
   length: 255
   unique: true
 lifecycleCallbacks:
  prePersist: [ setCreatedAtValue, setTokenValue ]
  preUpdate: [ setUpdatedAtValue ]
