Lc\LcBundle\Entity\Friend:
 type: entity
 repositoryClass: Lc\LcBundle\Repository\FriendRepository
 table: friend
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  status:
   type: boolean
  is_confirmed:
   type: boolean
  cast:
   type: boolean
   nullable: true
  created_at:
   type: datetime
  updated_at:
   type: datetime
   nullable: true
  token:
   type: string
   length: 255
   unique: true
 manyToOne:
  user1:
   targetEntity: User
   inversedBy: friend1
   joinColumn:
    name: user
    referencedColumnName: id
  user2:
   targetEntity: User
   inversedBy: friend2
   joinColumn:
    name: friend
    referencedColumnName: id
 lifecycleCallbacks:
  prePersist: [ setCreatedAtValue, setTokenValue ]
  preUpdate: [ setUpdatedAtValue ]
