Lc\LcBundle\Entity\Glike:
 type: entity
 table: glike
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  created_at: 
   type: datetime
  updated_at:
   type: datetime
   nullable: true
  status:
   type: boolean
  token:
   type: string
   length: 255
   unique: true
 manyToOne:
  gallery:
   targetEntity: Gallery
   inversedBy: glike
   joinColumn:
    name: gallery_id
    referencedColumnName: id
  user:
   targetEntity: User
   inversedBy: glike
   joinColumn:
    name: user_id
    referencedColumnName: id
