Lc\LcBundle\Entity\Job:
 type: entity
 table: job
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  name:
   type: string
   length: 255
  token:
   type: string
   length: 255
   unique: true
  is_active:
   type: boolean
  created_at: 
   type: datetime
  updated_at:
   type: datetime
   nullable: true
 oneToMany:
  usercriteria:
   targetEntity: Usercriteria
   mappedBy: job
  profile:
   targetEntity: Profile
   mappedBy: job
