Lc\LcBundle\Entity\Notification:
 type: entity
 repositoryClass: Lc\LcBundle\Repository\NotificationRepository
 table: notification
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  viewed:
   type: boolean
  from_page:
   type: integer
  from_id:
   type: string
   length: 255
   nullable: true
  created_at:
   type: datetime
  updated_at:
   type: datetime
   nullable: true
  token:
   type: string
   length: 255
   unique: true
 manyToOne:
  user1:
   targetEntity: User
   inversedBy: notify1
   joinColumn:
    name: user1
    referencedColumnName: id
  user2:
   targetEntity: User
   inversedBy: notify2
   joinColumn:
    name: user2
    referencedColumnName: id
 lifecycleCallbacks:
  prePersist: [ setCreatedAtValue, setTokenValue ]
  preUpdate: [ setUpdatedAtValue ]
