Lc\LcBundle\Entity\Profile:
 type: entity
 table: profile
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  name:
   type: string
   length: 255
   nullable: true
  job:
   type: string
   length: 255
   nullable: true
  school:
   type: string
   length: 255
   nullable: true
  city:
   type: string
   length: 255
   nullable: true
  address:
   type: text
   nullable: true
  about:
   type: text
   nullable: true
  created_at:
   type: datetime
  updated_at:
   type: datetime
   nullable: true
  token:
   type: string
   length: 255
   unique: true
 oneToOne:
  user:
   targetEntity: User
   inversedBy: profile
   joinColumn:
    name: user_id
    referencedColumnName: id
 lifecycleCallbacks:
  prePersist: [ setCreatedAtValue, setTokenValue ]
  preUpdate: [ setUpdatedAtValue ]
