Lc\LcBundle\Entity\Sex:
 type: entity
 table: sex
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  name:
   type: string
   length: 255
  created_at:
   type: datetime
  updated_at:
   type: datetime
   nullable: true
  token:
   type: string
   length: 255
   unique: true
 oneToOne:
  usercriteria:
   targetEntity: Usercriteria
   mappedBy: sex
  profile:
   targetEntity: Profile
   mappedBy: sex
