Lc\LcBundle\Entity\Userlog:
 type: entity
 table: userlog
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  login_at:
   type: datetime
  last_login:
   type: datetime
   nullable: true
  logout_at:
   type: datetime
  last_logout:
   type: datetime
   nullable: true
  ip_address:
   type: string
   length: 255
  mac_address:
   type: string
   length: 255
  created_at:
   type: datetime
  updated_at:
   type: datetime
   nullable: true
  token:
   type: string
   length: 255
   unique: true  
 manyToOne:
  user:
   targetEntity: User
   inversedBy: userlog
   joinColumn:
    name: user_id
    referencedColumnName: id
