security:
    encoders:
        Lc\LcBundle\Entity\User:
         algorithm: bcrypt
         cost: 13

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        main:
            entity: { class: Lc\LcBundle\Entity\User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        create:
            pattern:  ^/user/create
            security: false
        wait:
            pattern:  ^/user/thanks
            security: false
        activate:
            pattern: ^/user/activate/{token}
            security: false
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /heaven
            logout:
                path:   /logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/heaven, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
