lc_lc_homepage:
    path:     /
    defaults: { _controller: LcLcBundle:Feeling:index }
# LcLcBundle_admin:
#         resource: "@LcLcBundle/Resources/config/routing/admin.yml"
#         prefix:   /heaven/admin
# LcLcBundle_admindoing:
#         resource: "@LcLcBundle/Resources/config/routing/admindoing.yml"
#         prefix:   /heaven/admindoing
# LcLcBundle_adminlog:
#         resource: "@LcLcBundle/Resources/config/routing/adminlog.yml"
#         prefix:   /heaven/adminlog
LcLcBundle_chat:
        resource: "@LcLcBundle/Resources/config/routing/chat.yml"
        prefix:   /heaven/chat
LcLcBundle_city:
        resource: "@LcLcBundle/Resources/config/routing/city.yml"
        prefix:   /heaven/city
LcLcBundle_controllerlist:
        resource: "@LcLcBundle/Resources/config/routing/controllerlist.yml"
        prefix:   /heaven/controllerlist
LcLcBundle_criteria:
        resource: "@LcLcBundle/Resources/config/routing/criteria.yml"
        prefix:   /heaven/criteria
LcLcBundle_education:
        resource: "@LcLcBundle/Resources/config/routing/education.yml"
        prefix:   /heaven/education
LcLcBundle_fcomment:
        resource: "@LcLcBundle/Resources/config/routing/fcomment.yml"
        prefix:   /heaven/fcomment
LcLcBundle_feeling:
        resource: "@LcLcBundle/Resources/config/routing/feeling.yml"
        prefix:   /heaven
LcLcBundle_flike:
        resource: "@LcLcBundle/Resources/config/routing/flike.yml"
        prefix:   /heaven/flike
LcLcBundle_friend:
        resource: "@LcLcBundle/Resources/config/routing/friend.yml"
        prefix:   /heaven/friend
LcLcBundle_fshare:
        resource: "@LcLcBundle/Resources/config/routing/fshare.yml"
        prefix:   /heaven/fshare
LcLcBundle_gallery:
        resource: "@LcLcBundle/Resources/config/routing/gallery.yml"
        prefix:   /heaven/gallery
LcLcBundle_glike:
        resource: "@LcLcBundle/Resources/config/routing/glike.yml"
        prefix:   /heaven/glike
LcLcBundle_gcomment:
        resource: "@LcLcBundle/Resources/config/routing/gcomment.yml"
        prefix:   /heaven/gcomment
LcLcBundle_gshare:
        resource: "@LcLcBundle/Resources/config/routing/gshare.yml"
        prefix:   /heaven/gshare
LcLcBundle_hobby:
        resource: "@LcLcBundle/Resources/config/routing/hobby.yml"
        prefix:   /heaven/hobby
LcLcBundle_job:
        resource: "@LcLcBundle/Resources/config/routing/job.yml"
        prefix:   /heaven/job
LcLcBundle_methodlist:
        resource: "@LcLcBundle/Resources/config/routing/methodlist.yml"
        prefix:   /heaven/methodlist
LcLcBundle_notification:
        resource: "@LcLcBundle/Resources/config/routing/notification.yml"
        prefix:   /heaven/notification
LcLcBundle_plan:
        resource: "@LcLcBundle/Resources/config/routing/plan.yml"
        prefix:   /heaven/plan
LcLcBundle_profile:
        resource: "@LcLcBundle/Resources/config/routing/profile.yml"
        prefix:   /heaven/profile
LcLcBundle_province:
        resource: "@LcLcBundle/Resources/config/routing/province.yml"
        prefix:   /heaven/province
LcLcBundle_religy:
        resource: "@LcLcBundle/Resources/config/routing/religy.yml"
        prefix:   /heaven/religy
LcLcBundle_sallary:
        resource: "@LcLcBundle/Resources/config/routing/sallary.yml"
        prefix:   /heaven/sallary
LcLcBundle_sex:
        resource: "@LcLcBundle/Resources/config/routing/sex.yml"
        prefix:   /heaven/sex
LcLcBundle_status:
        resource: "@LcLcBundle/Resources/config/routing/status.yml"
        prefix:   /heaven/status
LcLcBundle_user:
        resource: "@LcLcBundle/Resources/config/routing/user.yml"
        prefix:   /
LcLcBundle_usercriteria:
        resource: "@LcLcBundle/Resources/config/routing/usercriteria.yml"
        prefix:   /heaven/usercriteria
LcLcBundle_userdoing:
        resource: "@LcLcBundle/Resources/config/routing/userdoing.yml"
        prefix:   /heaven/userdoing
LcLcBundle_userlog:
        resource: "@LcLcBundle/Resources/config/routing/userlog.yml"
        prefix:   /heaven/userlog
login:
    pattern:   /login
    defaults:  { _controller: LcLcBundle:Default:login }
login_check:
    pattern:   /login_check
    defaults:  { _controller: LcLcBundle:Default:login }
logout:
    pattern:   /logout
repair:
    pattern:   /repair/{token}
    defaults:  { _controller: LcLcBundle:Default:repair }
forgot:
    pattern:   /forgot
    defaults:  { _controller: LcLcBundle:Default:forgot }
redirectPlaystore:
    pattern:   /aku-mau-order
    defaults:  { _controller: LcLcBundle:Default:redirectPlaystore }
agreement:
    pattern:   /agreement
    defaults:  { _controller: LcLcBundle:Default:agreement }
LcLcBundle_orderan:
    resource: "@LcLcBundle/Resources/config/routing/orderan.yml"
    prefix:   /orderan
