parameters:
#    lc_lc.example.class: Lc\LcBundle\Example

services:
#    lc_lc.example:
#        class: %lc_lc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
parameters:
    my_user_provider.class: Lc\LcBundle\Entity\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]
