Lc\LcBundle\Entity\User:
 constraints:
  - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
     fields: [email]
     errorPath: email
     message: 'Gunakan alamat email lain, email tersebut sudah digunakan.'
 properties:
  sex:
   - NotBlank:
      message: 'Pilih jenis kelamin.'
  email:
   - Email:
      message: 'Alamat email tidak benar.'
   - NotBlank:
      message: 'Email harap diisi.'
  birthday:
   - NotBlank:
      message: 'Tanggal lahir harap diisi.'
   - ContainsAlphanumeric: ~
  password2:
   - NotBlank:
      message: 'Ulangi password harap diisi.'
   - ComparePassword: 
      field: password
  password:
   - NotBlank:
      message: 'Password harap diisi.'
Lc\LcBundle\Entity\Feeling:
  feel:
   - NotBlank:
      message: 'Tulis apa yang sedang kamu rasakan.'
Lc\LcBundle\Entity\Fcomment:
  comment:
   - NotBlank:
      message: 'Tulis apa komentarmu.'
