Lc\LcBundle\Entity\User:
 constraints:
  - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
     fields: [email]
     errorPath: email
     message: 'Gunakan alamat email lain, email tersebut sudah digunakan.'
 properties:
  file:
   - Image: ~
  sex:
   - NotBlank:
      message: 'Pilih jenis kelamin.'
  email:
   - Email:
      message: 'Alamat email tidak benar.'
   - NotBlank:
      message: 'Email harap diisi.'
   - Length:
      max: 70
      maxMessage: 'Email mu melebihi batas maksimal karater, maksimal {{ limit }} karater.'
  birthday:
   - NotBlank:
      message: 'Tanggal lahir harap diisi.'
  password2:
   - NotBlank:
      message: 'Ulangi password harap diisi.'
   - Lc\LcBundle\Validator\Constraints\ComparePassword:
      field: password
  password:
   - NotBlank:
      message: 'Password harap diisi.'
   - Length:
      max: 30
      maxMessage: 'Password mu melebihi batas maksimal karater, maksimal {{ limit }} karater.'
  fullname:
   - NotBlank:
      message: 'Nama Lengkap harap diisi.'
   - Length:
      max: 50
      maxMessage: 'Nama mu melebihi batas maksimal karater, maksimal {{ limit }} karater.'
Lc\LcBundle\Entity\Feeling:
 properties:
  feel:
   - NotBlank:
      message: 'Tulis apa yang ingin kamu bagikan.'
   - Length:
      max: 108500
      maxMessage: 'Postingan mu melibihi batas maksimal jumlah karater, maksimal {{ limit }} karater.'
Lc\LcBundle\Entity\Orderan:
 properties:
  address:
   - NotBlank:
      message: 'Alamat tidak boleh kosong.'
  delivery_date:
   - NotBlank:
      message: 'Tanggal pengiriman tidak boleh kosong.'
  phone_wa:
   - NotBlank:
      message: 'Nomor WhatsApp tidak boleh kosong.'
Lc\LcBundle\Entity\Profile:
 properties:
  name:
   - NotBlank:
      message: 'Mohon isi nama.'
   - Length:
      max: 200
      maxMessage: 'Nama mu melibihi batas maksimal jumlah karater, maksimal {{ limit }} karater.'
  about:
   - Length:
      max: 10850
      maxMessage: 'Kolom tentang melibihi batas maksimal jumlah karater, maksimal {{ limit }} karater.'
  address:
   - Length:
      max: 10850
      maxMessage: 'Kolom alamat melibihi batas maksimal jumlah karater, maksimal {{ limit }} karater.'
  job:
   - Length:
      max: 200
      maxMessage: 'Kolom pekerjaan melibihi batas maksimal jumlah karater, maksimal {{ limit }} karater.'
  school:
   - Length:
      max: 200
      maxMessage: 'Kolom sekolah melibihi batas maksimal jumlah karater, maksimal {{ limit }} karater.'
  city:
   - Length:
      max: 200
      maxMessage: 'Kolom kota/kabupaten melibihi batas maksimal jumlah karater, maksimal {{ limit }} karater.'
Lc\LcBundle\Entity\Foto:
  foto:
   - Image:
      message: 'Pilih file foto/image.'
Lc\LcBundle\Entity\Fcomment:
  properties:
   comment:
    - NotBlank:
       message: 'Tulis apa komentarmu.'
    - Length:
       max: 10850
       maxMessage: 'Postingan mu melibihi batas maksimal jumlah karater, maksimal {{ limit }} karater.'
